---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-liveness-pod-origin
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 5