---
# 디플로이먼트
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver
  namespace: metallb-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webserver-loadbalancer-svc
  namespace: metallb-system
spec:
  type: LoadBalancer
  clusterIP: 10.100.10.10
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80
