---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-nginx-deploy
spec:
  replicas: 3
  selector:           # deployment 와 RS 연동 부분
    matchLabels:
      app: webapp
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14
          ports:
            - containerPort: 80