---
kind: Service
apiVersion: v1
metadata:
  name: webapp-nodeport-svc
spec:
  type: NodePort
  clusterIP: 10.100.10.10
  selector:
    app: webapp
  ports:
    - port: 80 #외부에서 들어오는 port
      targetPort: 80 # containerPort 동일
      nodePort: 30000
      