---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-pod
  annotations:
    kubernetes.io/change-cause: version 2.2
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 2
  selector:
    matchLabels:
      web: apache
      app: main
      rel: stable
      tier: frontend
  template:
    metadata:
      name: apache-pod
      labels:
        web: apache
        app: main
        rel: stable
        tier: frontend
    spec:
      containers:
        - name: web-apache
          image: httpd:2.2
          ports:
            - containerPort: 80